import localFont from "next/font/local";
import "./globals.css";
import { PropsWithChildren } from 'react';

const myFont = localFont({ src: './NotoSansJP-VariableFont_wght.ttf' });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body className={myFont.className}>{children}</body>
    </html>
  );
}
